export const SAVE_PRODUCT_INITIATED = "SAVE_PRODUCT_INITIATED";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_ERROR = "SAVE_PRODUCT_ERROR";

export const GET_PRODUCT_INITIATED = "GET_PRODUCT_INITIATED";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";

export const DELETE_PRODUCT_INITIATED = "DELETE_PRODUCT_INITIATED";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR";


