export const LOADER_STATUS = "LOADER_STATUS";
export const ERROR_NOT_AUTHORIZED = "ERROR_NOT_AUTHORIZED";
export const ERROR_HANDLER = "ERROR_HANDLER";
export const ERROR_EMPTY = "ERROR_EMPTY";
export const REDIRECT_LOGIN = "REDIRECT_LOGIN";
export const COLLAPS_MENU = "COLLAPS_MENU";
